#!/usr/bin/env python3
"""
Generate an xcube service config for local Terrascope RHOW Zarr tiles.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


DEFAULT_ZARR_ROOT = Path(
    "/home/pabrojast/Proyectos/stacprocess-ihp/data/terrascope_rhow_all_grids_full_history_zarr"
)
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent / "xcube_ukraine_rhow_local_config.yml"
)

# Excludes PIXELCLASSIFICATION by request.
ALLOWED_SUFFIX_TO_VAR = {
    "aot": "AOT",
    "raa": "RAA",
    "sza": "SZA",
    "vza": "VZA",
    "b01": "B01",
    "b02": "B02",
    "b03": "B03",
    "b04": "B04",
    "b05": "B05",
    "b06": "B06",
    "b07": "B07",
    "b08": "B08",
    "b11": "B11",
    "b12": "B12",
    "b8a": "B8A",
}

STORE_RE = re.compile(r"^(?P<tile>\d{2}[A-Z]{3})_(?P<suffix>[a-z0-9]+)_ts\.zarr$")

RANGES = {
    "AOT": [0.0, 1.0],
    "RAA": [0.0, 180.0],
    "SZA": [0.0, 90.0],
    "VZA": [0.0, 90.0],
    "B01": [0.0, 0.25],
    "B02": [0.0, 0.25],
    "B03": [0.0, 0.25],
    "B04": [0.0, 0.25],
    "B05": [0.0, 0.25],
    "B06": [0.0, 0.25],
    "B07": [0.0, 0.25],
    "B08": [0.0, 0.25],
    "B11": [0.0, 0.25],
    "B12": [0.0, 0.25],
    "B8A": [0.0, 0.25],
}


def _discover_stores(root: Path) -> list[tuple[str, str, str]]:
    stores: list[tuple[str, str, str]] = []
    for zarr_path in sorted(root.glob("*_ts.zarr")):
        if not zarr_path.is_dir():
            continue
        match = STORE_RE.match(zarr_path.name)
        if not match:
            continue
        tile = match.group("tile")
        suffix = match.group("suffix")
        var = ALLOWED_SUFFIX_TO_VAR.get(suffix)
        if not var:
            continue
        stores.append((tile, var, zarr_path.name))
    return stores


def _build_yaml(
    root: Path, stores: list[tuple[str, str, str]], enabled: bool
) -> str:
    lines: list[str] = []
    lines.append("# Auto-generated by generate_ukraine_rhow_xcube_config.py")
    lines.append("# Terrascope RHOW tiles (Ukraine, local filesystem store).")
    lines.append("# PIXELCLASSIFICATION is intentionally excluded.")
    if not enabled:
        lines.append("# RHOW/RHOB datasets are intentionally disabled.")
    lines.append("")
    lines.append("DataStores:")
    lines.append("  - Identifier: terrascope_rhow_local")
    lines.append("    StoreId: file")
    lines.append("    StoreParams:")
    lines.append(f'      root: "{root.as_posix()}"')
    lines.append("      max_depth: 1")

    if enabled:
        lines.append("    Datasets:")
        for tile, var, dataset_name in stores:
            ds_id = f"ua_rhow_{tile.lower()}_{var.lower()}"
            lines.append(f"      - Identifier: {ds_id}")
            lines.append(f'        Title: "Ukraine RHOW Tile {tile} {var}"')
            lines.append("        BoundingBox: [22.0, 44.0, 40.5, 52.5]")
            lines.append(f'        Path: "{dataset_name}"')
            lines.append("        Style: rhow_default")
            lines.append("        AccessControl:")
            lines.append("          RequiredScopes: []")
    else:
        lines.append("    Datasets: []")

    lines.append("")
    if enabled:
        lines.append("Styles:")
        lines.append("  - Identifier: rhow_default")
        lines.append("    ColorMappings:")
        for var in sorted({var for _, var, _ in stores}):
            lo, hi = RANGES.get(var, [0.0, 1.0])
            lines.append(f"      {var}:")
            lines.append('        ColorBar: "viridis"')
            lines.append(f"        ValueRange: [{lo}, {hi}]")
    else:
        lines.append("Styles: []")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate xcube YAML for local Ukraine RHOW Zarr tiles."
    )
    parser.add_argument(
        "--zarr-root",
        type=Path,
        default=DEFAULT_ZARR_ROOT,
        help="Directory containing RHOW *_ts.zarr tile stores.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output YAML config path.",
    )
    parser.add_argument(
        "--enable-rhow",
        action="store_true",
        help="Enable RHOW datasets in generated config. Default is disabled.",
    )
    args = parser.parse_args()

    zarr_root = args.zarr_root.expanduser().resolve()
    output_path = args.output.expanduser().resolve()

    stores: list[tuple[str, str, str]] = []
    if args.enable_rhow:
        if not zarr_root.exists():
            raise SystemExit(f"Zarr root does not exist: {zarr_root}")
        if not zarr_root.is_dir():
            raise SystemExit(f"Zarr root is not a directory: {zarr_root}")

        stores = _discover_stores(zarr_root)
        if not stores:
            raise SystemExit(
                "No RHOW stores found in root. Expected names like 36TXT_b02_ts.zarr."
            )

    yaml_text = _build_yaml(zarr_root, stores, enabled=args.enable_rhow)
    output_path.write_text(yaml_text, encoding="utf-8")

    print(f"Generated {output_path}")
    print(f"Store root: {zarr_root}")
    print(f"RHOW enabled: {args.enable_rhow}")
    print(f"Datasets: {len(stores)}")
    if args.enable_rhow:
        vars_found = sorted({var for _, var, _ in stores})
        print("Variables: " + ", ".join(vars_found))


if __name__ == "__main__":
    main()
